V2 ips metadata
lukashino/suricata pull request #44
Opened 2022-11-28 13:51 UTC by AndreiShchepa

2022-11-29 11:31 UTC, lukashino commented on dpdk/prefilter/metadata.c
> +    }
else if should be on the same line as the closing bracket

2022-11-29 11:31 UTC, lukashino commented on dpdk/prefilter/metadata.c
> +int decodePacketL4(uint8_t proto, size_t size, unsigned char *ptr, metadata_t *metaData, uint16_t len)
The function name can be metadata connected - although the metadata extraction and extraction of flow keys for bypass needs to be merged to not decode the packet twice. 
You could also reorganize the arguments in the function so that "the most important" ones are at the beginning  - either `metadata` or `ptr`. Ptr could be also named more appropriately maybe like pkt_l4_layer. The `ptr` type should be defined as `uint8_t *` - avoid unsigned char and even int as types and use types of e.g. `(u)int(8,16,32)_t`

2022-11-29 11:31 UTC, lukashino commented on dpdk/prefilter/metadata.c
> +int decodePacketIPv4(uint16_t len, metadata_t *metaData) {
My preference would be to have the important argument at the beginning so switch the order of the two arguments. Also, function arguments should follow snake_case convention.

2022-11-29 11:31 UTC, lukashino commented on dpdk/prefilter/metadata.c
> +int decodePacketIPv4(uint16_t len, metadata_t *metaData) {
Function names should follow CamelCase with the initial capital letter

2022-11-29 15:37 UTC, lukashino requested changes

2022-11-29 15:37 UTC, lukashino commented on dpdk/prefilter/prefilter.c
> +    Log().debug("PPP Action for %s", IPC_ACTION_SET_UP_OFFLOADS);
What's PPP action?

2022-11-29 15:37 UTC, lukashino commented on dpdk/prefilter/prefilter.c
> +    sleep(2);
Are you sure, we need 2 seconds of sleep here? Maybe `LcoreStateCheckAllWTimeout(LCORE_OFFLOADS_INIT, tout_sec);` would be a better option.

2022-11-29 15:37 UTC, lukashino commented on src/decode.h
> +enum oofldsIdxsPf {
typo `oo..` ?

2022-11-29 15:37 UTC, lukashino commented on src/decode.h
> +enum oofldsIdxsPf {
Also apply CamelCase

2022-11-29 15:37 UTC, lukashino commented on src/decode.h
> +    uint16_t PFl4_len;
PF_l4_len

2022-11-29 15:37 UTC, lukashino commented on src/decode.h
> +    uint16_t PFl4_len;
I would rather move this code to the DPDK vars

2022-11-29 15:37 UTC, lukashino commented on src/decode.h
> +    uint16_t PFl4_len;
`DPDKPacketVars dpdk_v;`

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +    .ofldsFromPfToSur = {
snake_case

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +        .Ipv4 = "IPV4",
lowercase

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +    config = ConfGetNode("offloadsFromPfToSur");
DPDK metadata configuration should be under individual interfaces or at least under DPDK section.

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +            iconf->mempool_cache_size, 128, mbuf_size, (int)iconf->socket_id);
Size of the private space should be calculated based on the enabled offloads and not be fixed to 128B

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +    mz = rte_memzone_lookup(memzone_name);
probably not required changes?

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +void setOffloads(uint16_t finalOffloads, uint16_t* cntOffloads, uint16_t* indexOffloads)
adjust naming

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +void setOffloads(uint16_t finalOffloads, uint16_t* cntOffloads, uint16_t* indexOffloads)
pointer asterisks should be on the variable side (`char *ptr`)

2022-11-29 15:37 UTC, lukashino commented on src/runmode-dpdk.c
> +    config = ConfGetNode("offloadsFromPfToSur");
Per-interface metadata support is prefered

2022-11-29 15:37 UTC, lukashino commented on src/source-dpdk.c
> +                        p->metadata_flags |= (1 << IPV4_ID);
I am not sure if you use metadata IDs somewhere as a number but if you case about bit shifts only you are better off defining macros for that (`#define METADATA_ID_IPV4       1 << 3`)

2022-11-29 15:37 UTC, lukashino commented on src/util-dpdk-bypass.h
> +#define IPC_ACTION_SET_UP_OFFLOADS "set_up_offloads"
Apply generic->specific naming so would be better as `offloads_setup`

2022-11-29 15:37 UTC, lukashino commented on src/util-error.h
> +    SC_ERR_OFFLOADS,
add DPDK reference so `SC_ERR_DPDK_OFFLOADS`
and also add what part of offloads has failed so e.g. `SC_ERR_DPDK_OFFLOADS_INIT`

2022-11-30 10:19 UTC, AndreiShchepa commented on dpdk/prefilter/metadata.c
> +#if 0
deleted

2022-11-30 11:56 UTC, AndreiShchepa commented on src/runmode-dpdk.c
> +    mz = rte_memzone_lookup(memzone_name);
restored

2022-11-30 12:00 UTC, AndreiShchepa commented on dpdk/prefilter/prefilter.c
> +    Log().debug("PPP Action for %s", IPC_ACTION_SET_UP_OFFLOADS);
IPC*

2022-12-05 13:15 UTC, AndreiShchepa commented on dpdk/prefilter/prefilter.c
> +    sleep(2);
wait LCORE_OFFLOADS_DONE state, done

2023-05-11 17:18 UTC, lukashino commented
continues in #52

2023-05-11 17:18 UTC, closed without merging